### ISSUE TITLE
Error attempting to duplicate npc actor

### ISSUE THREAD

**Issue by mcglincy** [mcglincy/frontierscum-foundry-vtt#1]
actor.js:9 Uncaught (in promise) TypeError: Cannot set property token of #<Actor> which has only a getter
    at FSActor.create (actor.js:9:16)
    at FSActor.clone (commons.js:6021:38)
    at Object.callback (foundry.js:60766:27)
    at #onClickItem (foundry.js:55711:11)
    at HTMLElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)

**Comment by mcglincy** [comment]
Fixed in 1.0.1.
